CreateThread(function()
    -- Cuerpos de Seguridad Españoles
    AddTextEntry('POLICE', 'Citroen C4 Picasso - CNP Patrulla')
    AddTextEntry('POLICE2', 'Peugeot 308 - CNP Z')
    AddTextEntry('POLICE3', 'Seat Leon FR - Guardia Civil Trafico')
    AddTextEntry('POLICE4', 'Nissan Pathfinder - Guardia Civil')
    AddTextEntry('POLICEB', 'BMW R1200RT - Moto Guardia Civil')
    AddTextEntry('RIOT', 'Mercedes Sprinter - UIP Antidisturbios CNP')
    AddTextEntry('AMBULANCE', 'Mercedes Sprinter - SAMUR Urgencias')
    AddTextEntry('FIRETRUK', 'Camion de Bomberos de Espana')

    -- Vehículos Reales de Calle (Superdeportivos, berlinas y motos)
    AddTextEntry('ADDER', 'Bugatti Veyron Super Sport')
    AddTextEntry('NERO', 'Bugatti Chiron W16')
    AddTextEntry('ZENTORNO', 'Lamborghini Sesto Elemento')
    AddTextEntry('REAPER', 'Lamborghini Huracan LP 610-4')
    AddTextEntry('VACCA', 'Lamborghini Gallardo')
    AddTextEntry('TEMPESTA', 'Lamborghini Huracan Performante')
    AddTextEntry('ITALIGTB', 'Ferrari 488 GTB')
    AddTextEntry('TURISMOR', 'Ferrari LaFerrari')
    AddTextEntry('T20', 'McLaren P1 Hybrid')
    AddTextEntry('GP1', 'McLaren F1')
    AddTextEntry('OSIRIS', 'Pagani Huayra')
    AddTextEntry('TAILGATER', 'Audi RS6 Avant Quattro')
    AddTextEntry('TAILGATER2', 'Audi RS3 Sportback')
    AddTextEntry('SCHAFTER2', 'Mercedes-Benz Clase C 63 AMG')
    AddTextEntry('SCHAFTER3', 'Mercedes-Benz Clase E 63 AMG')
    AddTextEntry('DUBSTA', 'Mercedes-Benz Clase G 63 AMG')
    AddTextEntry('SENTINEL', 'BMW M3 E92 V8')
    AddTextEntry('ORACLE', 'BMW M5 F90')
    AddTextEntry('COMET2', 'Porsche 911 GT3 RS')
    AddTextEntry('ELEGY', 'Nissan GT-R R35 Nismo')
    AddTextEntry('SULTAN', 'Subaru Impreza WRX STI')
    AddTextEntry('BALLER', 'Range Rover Sport SVR')
    AddTextEntry('FELON', 'Maserati Ghibli Trofeo')
    AddTextEntry('BANSHEE', 'Dodge Viper ACR')
    AddTextEntry('COQUETTE', 'Chevrolet Corvette C7 Stingray')
    
    -- Motos Reales
    AddTextEntry('BATI', 'Ducati Panigale V4')
    AddTextEntry('AKUMA', 'Ducati Monster 1200')
    AddTextEntry('HAKUCHOU', 'Suzuki Hayabusa 1300')
    AddTextEntry('SANCHEZ', 'Yamaha YZ450F Motocross')
    AddTextEntry('FAGGIO', 'Vespa Piaggio 125cc')
end)
